version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/Resistance.Postgres"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
  - package-ecosystem: "nuget"
    directory: "/src/Resistance.Postgres.NodaTime"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
